namespace BrandUp.CardDav.VCard
{
    public enum Parameter
    {
        LANGUAGE,
        VALUE,
        PREF,
        ALTID,
        PID,
        TYPE,
        MEDIATYPE,
        CALSCALE,
        SORTAS,
        GEO,
        TZ
    }

    public enum CardProperty
    {
        SOURCE,
        KIND,
        XML,
        FN,
        N,
        NICKNAME,
        PHOTO,
        BDAY,
        ANNIVERSARY,
        GENDER,
        ADR,
        TEL,
        EMAIL,
        IMPP,
        LANG,
        TZ,
        GEO,
        TITLE,
        ROLE,
        LOGO,
        ORG,
        MEMBER,
        RELATED,
        CATEGORIES,
        NOTE,
        PRODID,
        REV,
        SOUND,
        UID,
        CLIENTPIDMAP,
        URL,
        VERSION,
        KEY,
        FBURL,
        CALADRURI,
        CALURI
    }
}
